### PR TITLE
Add EasyAdmin Configuration

### PR DESCRIPTION
**Pull request by Beagon**
Hi all,

I really wanted this bundle to be used in my project but I didn't want to have yet another admin panel, so I integrated it into the config of EasyAdminBundle which I was already using. I think a lot of people would enjoy to use this too so I propose this as a new feature that can be added to the bundle itself.

To do:
- [x] Create configuration
- [x] Add the option to the documentation.
- [ ] Translations (?)

If you think this idea is bonkers or shouldn't be default in the bundle, feel free to decline the PR.

All feedback is welcome!

Greetings,

Robin

Screenshots:

- List:
List

- Create:
Create

- Edit:
Edit

### CODE REVIEW

**Comment by phansys** [comment]
IMO, this kind of additions should be provided via **suggested** dependendency (creating a new library for this purpose), where you can declare the **required** range of versions for EasyAdminBundle, in order to ensure the configuration you're providing is fully compatible with the resolved version.
See #117 for more context about this reasoning.

**Comment by J-Mose** [comment]
Hi, 

As an EasyAdmin user, i think provide a configuration template is a good approach as it wont add any require package to the bundle.

What is the minimal easyadmin version for your configuration ? So we can add it to the suggested packages.

**Comment by phansys** [comment]
Hi!
I'm not using EasyAdmin. I'm talking about that providing configuration for a package that is not handled as a requirement of this bundle is not a good idea, since you haven't control over which version of that package the consumer of this bundle have installed, so the provided configuration could not work as expected between different versions (released or yet unreleased).
Nor do I believe that the solution is to add "easycorp/easyadmin-bundle" to bundle requirements, since IMHO providing an admin is out of the scope of this bundle.
As I mentioned before, I think a better approach to leverage the configuration added in this PR is to provide it with a new bundle ("EasyAdminCommandSchedulerBundle" or so), which the users can optionally install if they need to handle the scheduled commands with EasyAdmin. Of course, this new bundle must have "easycorp/easyadmin-bundle" and "jmose/command-scheduler-bundle" as requirements with its explicit supported version constraints. Finally, "jmose/command-scheduler-bundle" could add "EasyAdminCommandSchedulerBundle" as a suggested dependency.
I think with this dependency structure, the responsibilities of this bundle can avoid the pollution of aspects that are outside of its core while it can trust that the integrations with third party libraries can be handled in a robust way.

**Comment by J-Mose** [comment]
@phansys , i understand your concern, but in this PR, the easyadmin configuration won't be loaded by default. It's more like an example configuration and it won't add any "hard-dependencies".

But maybe we could just provide this configuration in the documentation and let the consumers copy/paste or customize it if needed.

**Comment by phansys** [comment]
It could be a much better decision, I think. Thank you!

**Comment by TavoNiievez** [comment]
Hi,
I copied and pasted this configuration into one of my projects and it works correctly.
I also added Spanish translations with the 'label' tag and share them here in case it helps in any way. Thank you very much.

This is my final configuration.
'\...\config\packages\easy_admin\cron.yaml'

```
easy_admin:
  entities:
    Cron:
      role: ROLE_EMPLOYEE
      label: 'Programador'
      class: JMose\CommandSchedulerBundle\Entity\ScheduledCommand
      list:
        title: "Programador de Comandos CRON"
        fields:
          - { property: 'id', label: 'ID' }
          - { property: 'name', label: 'Nombre' }
          - { property: 'command', label: 'Comando' }
          - { property: 'arguments', label: 'Argumentos' }
          - { property: 'lastExecution', label: 'Última ejecución' }
          - { property: 'lastReturncode', label: 'Último código de retorno' }
          - { property: 'locked', label: 'Bloqueado', type: 'boolean' }
          - { property: 'priority', label: 'Prioridad' }
          - { property: 'disabled', label: 'Inhabilitado' }
        form_filters:
          - { property: 'disabled', label: 'Inhabilitado' }
          - { property: 'locked', label: 'Bloqueado' }
      form:
        fields:
          - { type: 'section', label: 'Detalles del comando' }
          - { property: 'name', label: 'Nombre' }
          - { property: 'command', label: 'Comando', type: 'JMose\CommandSchedulerBundle\Form\Type\CommandChoiceType' }
          - { property: 'arguments', label: 'Argumentos' }
          - { property: 'cronExpression', label: 'Expresión CRON' }
          - { property: 'priority', label: 'Prioridad' }
          - { property: 'disabled', label: 'Inhabilitado' }
          - { type: 'section', label: 'Configuración miscelánea' }
          - { property: 'logFile', label: 'Archivo de Registro' }
      new:
        fields:
          - { property: 'executeImmediately', label: 'Ejecutar de inmediato' }

```
The role stuff comes from the alterphp extensions bundle.

And in my 'config/packages/easy_admin.yaml' : 

`      - { entity: 'Cron', label: 'Programador', icon: 'tasks' }`

**Comment by J-Mose** [comment]
Close this PR in favor of #123 
Thx to @Beagon !

**Pull request closed without merging**
