### PR TITLE
Argument parsing enhance

### PR DESCRIPTION
**Pull request by tikoflano**
This improves the way the scheduler works with arguments and options that include a white space. Before this the scheduler would fail to set an option like **--my-option="my value"** because it used to `explode` at the white spaces.

Now the function `ScheduledCommand->getArguments(true)` uses regex to separate each argument/option and it value. It still handles the options that don't have any value (flags) and sets that option to `true`.

I also added some clarification to the docs on how to use argument and options (addresing the first question on #55, the second one is a different issue I may work in if you need to)

### CODE REVIEW

**Comment by tikoflano** [comment]
I wrote some test for my function. The coverage decreased is caused no exception is thrown.

**Comment by J-Mose** [comment]
Thank you for these improvements  @tikoflano ! 👍

**Comment by tikoflano** [comment]
Do you plan to create a release soon? I use this library in some projects so I need to know if I need to change my composer to use the `master` branch or wait for the release.

**Comment by J-Mose** [comment]
v1.2.4 has been release

**Pull request merged**
