### PR TITLE
Add Symfony 4 support

### PR DESCRIPTION
**Pull request by sygnisoft**

### CODE REVIEW

**Comment by Gemineye** [comment]
Maybe you should allow older PHP Versions? Is there a reason for PHP 7+ only?

**Comment by gubler** [comment]
You also updated PHPUnit to 6.5, which replaced `\PHPUnit_Framework_TestCase` with `\PHPUnit\Framework\TestCase`. The travis builds I checked were dying when PHPUnit tried to run and couldn't find the old `\PHPUnit_Framework_TestCase` class.

I think replacing the `extends \PHUnit_Framework_TestCase` in each test with `extends TestCase` and add `use PHPUnit\Framework\TestCase;` in with the other `use` statements.

**Comment by gubler** [comment]
Technically, the `\PHPUnit_Framework_TestCase` class was deprecated in PHPUnit 5 and dropped in 6.5.

**Comment by gubler** [comment]
And (I assume) the reason for the 7.1 minimum is that is what is required by Symfony 4.

**Comment by Gemineye** [comment]
But is there a reason why you cannot use this Bundle with Symfony 3.4 and PHP 5?

**Comment by gubler** [comment]
Looking over the changes, I don't _think_ the PHP version needed to be bumped. The only changes were to the composer versions and the changes to the template paths. I think that can be changed back to `>=5.5.9` and the older version of PHP re-added to the `.travis.yml` file.

**Comment by gubler** [comment]
OK - I've done a bit more digging and (at least one) of the problems ends up being the PHPUnit's minimum version.

1. Symfony 4 conflicts with PHPUnit <5.4.3
2. PHPUnit 5.4 requires PHP 5.6
3. This bundle has a minimum PHP version of 5.5.9

There is no way to fix this without releasing a new version that drops PHP 5.5 support. Minimum PHP version would need to be bumped to 5.6 for PHPUnit 5.4 or 7.0 for PHPUnit 6.5.

**Comment by Gemineye** [comment]
Dropping 5.5 is not such a bad idea?! It has reached end of life 2 years ago!

**Comment by gubler** [comment]
I didn't say it was a bad idea. I was only saying that a new version release would need to be tagged if it was.

And if a new version was going to be done, I don't know if there are other issues that need to be resolved first.

**Comment by gubler** [comment]
I created pull request #96 as a starting place for a version 2, which makes the minimum version of Symfony to 3.4 and PHP 7.0.8. It also supports Symfony 4.0.

**Comment by J-Mose** [comment]
Cover by #89 and #96.

**Pull request closed without merging**
